//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_LMIGREATICE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class enteredData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enteredData()
        {
            this.glaciologicalDatas = new HashSet<glaciologicalData>();
            this.hydrologicalDatas = new HashSet<hydrologicalData>();
            this.metadatas = new HashSet<metadata>();
            this.meteorologicalDatas = new HashSet<meteorologicalData>();
        }

        public int idEnteredData { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("File Name")]
        public string nameEnteredData { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DataType(DataType.Date)]
        [DisplayName("Start Date")]
        public System.DateTime startDate { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DataType(DataType.Date)]
        [DisplayName("End Date")]
        public System.DateTime endDate { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Data Type")]
        public int idDataType { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Station")]
        public int idStation { get; set; }

        [DisplayName("User")]
        public int idSystemUser { get; set; }

        [DisplayName("State")]
        public bool stateR { get; set; }

        public virtual dataType dataType { get; set; }
        public virtual station station { get; set; }
        public virtual systemUser systemUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<glaciologicalData> glaciologicalDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hydrologicalData> hydrologicalDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metadata> metadatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meteorologicalData> meteorologicalDatas { get; set; }
    }
}
