//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_LMIGREATICE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class glaciologicalData
    {
        public int idMassBalanceData { get; set; }
        public string altitudinalBar { get; set; }
        public int startDay { get; set; }
        public int startMonth { get; set; }
        public int startYear { get; set; }
        public int endDay { get; set; }
        public int endMonth { get; set; }
        public int endYear { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public double altitude { get; set; }
        public double massBalance { get; set; }
        public int monthData { get; set; }
        public int idEnteredData { get; set; }
    
        public virtual enteredData enteredData { get; set; }
    }
}
