//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_LMIGREATICE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hydrologicalData
    {
        public int idHydrologicalData { get; set; }
        public DateTime dateData { get; set; }
        public double flow_Q_l_s_ { get; set; }
        public double h_cm_ { get; set; }
        public int idEnteredData { get; set; }
    
        public virtual enteredData enteredData { get; set; }
    }
}
