//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_LMIGREATICE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class institution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public institution()
        {
            this.systemUsers = new HashSet<systemUser>();
        }

        [DisplayName("Institution")]
        public int idInstitution { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [RegularExpression("[A-Z]+", ErrorMessage = "Must be written in capital letters. It can not contain numbers, spaces or special characters")]
        [DisplayName("Institution")]
        public string nameInstitution { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<systemUser> systemUsers { get; set; }
    }
}
