//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_LMIGREATICE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meteorologicalData
    {
        public int idMeteorologicalData { get; set; }
        public System.DateTime dateData { get; set; }
        public double inShortWaveRadiation { get; set; }
        public double outShortWaveRadiation { get; set; }
        public double albedo { get; set; }
        public Nullable<double> inLongWaveRadiation { get; set; }
        public Nullable<double> outLongWaveRadiation { get; set; }
        public double relativeHumidity { get; set; }
        public double ventilatedAirTemperature { get; set; }
        public Nullable<double> nonVentilatedAirTemperature { get; set; }
        public double windSpeed { get; set; }
        public double windDirection { get; set; }
        public Nullable<double> precipitationAmount { get; set; }
        public Nullable<double> precipitationRate { get; set; }
        public Nullable<double> distanceSensor_Snow { get; set; }
        public Nullable<double> snowDepth { get; set; }
        public Nullable<double> groundFlux { get; set; }
        public Nullable<double> groundTemp_3cm { get; set; }
        public Nullable<double> groundTemp_10cm { get; set; }
        public Nullable<double> groundTemp_30cm { get; set; }
        public int idEnteredData { get; set; }
    
        public virtual enteredData enteredData { get; set; }
    }
}
