//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_LMIGREATICE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class station
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public station()
        {
            this.enteredDatas = new HashSet<enteredData>();
        }

        public int idStation { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Name Station")]
        public string nameStation { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Location")]
        public int idLocation { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [RegularExpression("^-?([1-8]?[0-9]\\.{1}\\d{1,6}$|90\\.{1}0{1,6}$)", ErrorMessage = "INVALID CHARSET")]
        [DisplayName("Latitude")]
        public decimal latitudeStation { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [RegularExpression("^-?([1-8]?[0-9]\\.{1}\\d{1,6}$|90\\.{1}0{1,6}$)", ErrorMessage = "INVALID CHARSET")]
        [DisplayName("Longitude")]
        public decimal longitudeStation { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [RegularExpression("^[0-9]{1,4}$", ErrorMessage = "Altitude must be a positive integer from 1 to 9999")]
        [DisplayName("Altitude")]
        public double altitudeStation { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Glacier")]
        public int idGlacier { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Measurement Type")]
        public int idMeasurementType { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("State")]
        public bool stateR { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enteredData> enteredDatas { get; set; }
        public virtual glacier glacier { get; set; }
        public virtual location location { get; set; }
        public virtual measurementType measurementType { get; set; }
    }
}
