//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_LMIGREATICE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class systemUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public systemUser()
        {
            this.enteredDatas = new HashSet<enteredData>();
        }

        public int idSystemUser { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [RegularExpression("[A-Z]+", ErrorMessage = "Must be written in capital letters. It can not contain numbers, spaces or special characters")]
        [MaxLength(20, ErrorMessage = "Must be between 1 and 20 characters")]
        [DisplayName("First Name")]
        public string firstName { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [RegularExpression("[A-Z]+", ErrorMessage = "Must be written in capital letters. It can not contain numbers, spaces or special characters")]
        [MaxLength(20, ErrorMessage = "Must be between 1 and 20 characters")]
        [DisplayName("Last Name")]
        public string lastName { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [EmailAddress(ErrorMessage = "Not a valid Email")]
        [MaxLength(50)]
        [DisplayName("Email")]
        public string email { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [RegularExpression("^.*(?=.{6,64})[a-zA-Z0-9]+$", ErrorMessage = "Password must be between 6 and 64 characters. It can contain only letters and numbers.")]
        public string passwordU { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Gender")]
        public int idGender { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Title")]
        public int idTitle { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime dateOfBirth { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Country")]
        public int idCountry { get; set; }

        [Required(ErrorMessage = "Field Required")]
        [DisplayName("Institution")]
        public int idInstitution { get; set; }

        [DisplayName("Privilege")]
        public int idUserPrivilege { get; set; }

        [DisplayName("State")]
        public int idUserState { get; set; }

        public virtual country country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enteredData> enteredDatas { get; set; }
        public virtual gender gender { get; set; }
        public virtual institution institution { get; set; }
        public virtual title title { get; set; }
        public virtual userPrivilege userPrivilege { get; set; }
        public virtual userState userState { get; set; }
    }
}
